# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Denton
email: info@opendenton.com
description: > # this means to ignore newlines until "baseurl:"
  Open Denton is a community initiative to increase the usage and availability
  of open data in the city of Denton by engaging the public in civic technology
  and government transparency.
keywords: "open data, denton, open gov, tech, civic tech"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.opendenton.com" # the base hostname & protocol for your site
twitter_username: opendenton
github_username:  opendenton
facebook_username: opendenton

# Build settings
markdown: kramdown

# Gems
gems:
- jekyll-paginate
- jekyll-sitemap

# Analytics
google_analytics: "UA-48749943-1"
add_this: "ra-531d26532ab0a8ba"

# Commenting
disqus_shortname: "opendenton"

# Enable site search
search: false

# Devleopment options
sass:
  style: compressed

# Blog
paginate: 6
paginate_path: "/blog/page:num/"
